name: Google Cloud App Engine

on:
  workflow_run:
    workflows: [Node.js CI]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        # The deployment settings should list multiple services here.
        service: [default]
        entrypoint: [
          "node artifacts/default/bin/www"
        ]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Create config file'
      run: |
        cat >> app.yaml <<EOL
        runtime: nodejs18
        instance_class: F4
        automatic_scaling:
          max_instances: 1
          target_cpu_utilization: 0.8
          min_pending_latency: 900ms
          max_concurrent_requests: 50
        service: ${{ matrix.service }}
        entrypoint: ${{ matrix.entrypoint }}
        env_variables:
          DATABASE_SOCKET_PATH: /cloudsql/${{ secrets.DATABASE_CONNECTION_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SERVER_HOST: 0.0.0.0
          DEBUG: '*,-sequelize:*,-koa:*,-express:*'
        EOL

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - id: 'deploy'
      name: 'Deploy code to App Engine'
      uses: 'google-github-actions/deploy-appengine@v1'
